name: "publish"

on:
  push:
    tags:
      - "v*" # e.g. v1.0.0

jobs:
  publish-tauri-arm64:
    name: Build macOS arm64
    permissions:
      contents: write
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Install frontend dependencies
        run: npm ci

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        with:
          tagName: v__VERSION__
          releaseName: "Blueprint ALPHA v__VERSION__"
          releaseBody: "Source code, and compiled binaries for macOS ARM64."
          releaseDraft: true
          prerelease: false
          args: --target aarch64-apple-darwin
