name: Publish

on:
  push:
    tags:
      - 'v*'            # e.g. v1.0.0

jobs:
  # --------------------------------------------------------
  # 🍏 macOS Apple Silicon build (self-hosted)
  # --------------------------------------------------------
  publish-tauri-arm64:
    name: Build macOS arm64
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Install frontend dependencies
        run: npm ci

      - name: Import signing certificate
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo "$APPLE_CERTIFICATE" | base64 -d > certificate.p12

          # remove any leftover keychain so create always succeeds
          security delete-keychain build.keychain 2>/dev/null || true

          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
        with:
          tagName: v__VERSION__
          releaseName: 'Blueprint ALPHA v__VERSION__'
          releaseBody: 'Source code, and compiled binaries for macOS/Linux.'
          releaseDraft: true
          prerelease: false
          includeUpdaterJson: true   # ← auto-creates latest.json
          args: --target aarch64-apple-darwin

  # --------------------------------------------------------
  # 🍏 macOS Intel build (self-hosted)
  # --------------------------------------------------------
  publish-tauri-x64:
    name: Build macOS x86_64
    permissions:
      contents: write
    runs-on: self-hosted          # Intel runner
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin   # Intel target

      - name: Install frontend dependencies
        run: npm ci

      - name: Import macOS signing certificate
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo "$APPLE_CERTIFICATE" | base64 -d > certificate.p12
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
        with:
          tagName: v__VERSION__
          releaseName: 'Blueprint ALPHA v__VERSION__'
          releaseBody: 'Source code, and compiled binaries for macOS/Linux.'
          releaseDraft: true
          prerelease: false
          includeUpdaterJson: true
          args: --target x86_64-apple-darwin

  # --------------------------------------------------------
  # 🐧 Linux x86_64 build (Github-hosted)
  # --------------------------------------------------------
  publish-tauri-linux:
    name: Build Linux x86_64
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Install frontend dependencies
        run: npm ci

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: 'Blueprint ALPHA v__VERSION__'
          releaseBody: 'Source code, and compiled binaries for macOS/Linux.'
          releaseDraft: true
          includeUpdaterJson: true   # ← also uploads latest.json (only one copy is kept)
          args: ''