# name: publish
# on:
#   push:
#     tags:
#       - 'v*'        # e.g. v1.0.0

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# jobs:
#   publish-tauri:
#     permissions:
#       contents: write
#     strategy:
#       fail-fast: false
#       matrix:
#         include:
#           - platform: macos-latest
#             args: '--target x86_64-apple-darwin'
#           - platform: macos-latest
#             args: '--target aarch64-apple-darwin'
#           - platform: ubuntu-22.04
#             args: ''
#           - platform: windows-latest
#             args: ''
#     runs-on: ${{ matrix.platform }}
#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: lts/*
#           cache: 'npm'

#       - name: Install Rust stable
#         uses: dtolnay/rust-toolchain@stable
#         with:
#           targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

#       - name: Rust cache
#         uses: swatinem/rust-cache@v2

#       - name: Install Linux deps
#         if: matrix.platform == 'ubuntu-22.04'
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

#       - name: Install frontend deps
#         run: npm ci

#       - name: Build & publish
#         uses: tauri-apps/tauri-action@v0
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
#           TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
#           APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
#           APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
#           APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
#           WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
#           WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
#         with:
#           tagName: v__VERSION__
#           releaseName: 'App v__VERSION__'
#           releaseBody: 'See the assets below.'
#           releaseDraft: true
#           prerelease: false
#           args: ${{ matrix.args }}